#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION "2020.2.0f1"
#define UNITY_VERSION_DIGITS "2020.2.0"
#define UNITY_VERSION_SUFFIX "f1"
#define UNITY_VERSION_VER 2020
#define UNITY_VERSION_MAJ 2
#define UNITY_VERSION_MIN 0
#define UNITY_IS_BETA 0
